### ISSUE TITLE
Duplicate Lines

### ISSUE THREAD

**Issue by MasterCash** [JacobFischer/Creer#6]
https://github.com/siggame/Creer/blob/c1683ae999bcae12d0a318896505882a0f5deec4/creer/default.py#L104-L108

Unless I am mistaken, this is just a duplicated logic and one of them can be removed.

**Comment by JacobFischer** [comment]
Yup. There may have been some login in-between that got cleaned up and more clearly exposed this as an oversight now.

**Comment by JacobFischer** [comment]
If you'd like, you can throw together a PR here removing the duplicate lines to fix it
